import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./(context)/theme-provider";
import  Session  from "@/app/(context)/session-provider";
import { SubscriptionProvider } from "./(context)/SubscriptionContext";
import { Toaster } from "@/components/ui/toaster";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Session>
                <body className={`${outfit.className} dark:bg-[#18181B] dark:text-white `}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                    >
                       <SubscriptionProvider>
                       <Toaster/>
                        {children}</SubscriptionProvider>
                    </ThemeProvider>
                </body>
            </Session>
        </html>
    );
}
